version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  
    networks:
      - kafka-network

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 10.145.12.98
      KAFKA_CREATE_TOPICS: "wiki-changes:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    volumes:
      - ./data/kafka:/bitnami/kafka
    networks:
      - kafka-network

  spark:
    image: 'jupyter/all-spark-notebook:spark-3.1.1'
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    links:
      - "kafka:kafka-server"
    volumes:
      - ../notebook:/home/jovyan/work/notebooks/
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
